#ifndef SRC_TYPE_KIND_H_
#define SRC_TYPE_KIND_H_

namespace type {

enum Kind {
	INT_TYPE, DOUBLE_TYPE, STRING_TYPE, BOOL_TYPE, VOID_TYPE, ARRAY_TYPE, METHOD_TYPE, ERROR_TYPE
};

}

#endif /* SRC_TYPE_KIND_H_ */
